github: [metadata]

plugins:
  - jekyll-include-cache

remote_theme: "MichaelJCaruso/minimal-mistakes"

title: Vision
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: false
search_full_content: false

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"
      toc: true
      toc_label: "Contents"
      toc_sticky: true
